"""Removed InjuryLog models

Revision ID: 83500cc0713d
Revises: ec332ded933a
Create Date: 2026-05-30 20:12:28.721196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83500cc0713d'
down_revision = 'ec332ded933a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trial_attendance')
    op.drop_table('injury_logs')
    with op.batch_alter_table('trial_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trial_sessions_session_date'))

    op.drop_table('trial_sessions')
    op.drop_table('scouting_reports')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scouting_reports',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('player_id', sa.INTEGER(), nullable=False),
    sa.Column('scout_id', sa.INTEGER(), nullable=True),
    sa.Column('potential_rating', sa.VARCHAR(length=10), nullable=False),
    sa.Column('tactical_awareness', sa.TEXT(), nullable=True),
    sa.Column('physical_assessment', sa.TEXT(), nullable=True),
    sa.Column('conclusion', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scout_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trial_sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('location', sa.VARCHAR(length=100), nullable=False),
    sa.Column('session_date', sa.DATETIME(), nullable=False),
    sa.Column('session_type', sa.VARCHAR(length=30), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trial_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trial_sessions_session_date'), ['session_date'], unique=False)

    op.create_table('injury_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('player_id', sa.INTEGER(), nullable=False),
    sa.Column('injury_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('injured_on', sa.DATE(), nullable=False),
    sa.Column('cleared_on', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trial_attendance',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('trial_session_id', sa.INTEGER(), nullable=False),
    sa.Column('player_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('performance_rating', sa.INTEGER(), nullable=True),
    sa.Column('scout_feedback', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trial_session_id'], ['trial_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
