"""Initial migration for deployment

Revision ID: ec332ded933a
Revises: 
Create Date: 2026-05-28 19:35:47.764433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec332ded933a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opponent', sa.String(length=100), nullable=False),
    sa.Column('match_date', sa.DateTime(), nullable=False),
    sa.Column('venue', sa.String(length=100), nullable=True),
    sa.Column('our_score', sa.Integer(), nullable=False),
    sa.Column('their_score', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_match_date'), ['match_date'], unique=False)

    op.create_table('trial_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('session_date', sa.DateTime(), nullable=False),
    sa.Column('session_type', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trial_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trial_sessions_session_date'), ['session_date'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('player_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('preferred_foot', sa.String(length=10), nullable=True),
    sa.Column('primary_position', sa.String(length=20), nullable=False),
    sa.Column('current_weight_kg', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('player_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_profiles_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_profiles_primary_position'), ['primary_position'], unique=False)

    op.create_table('injury_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('injury_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('injured_on', sa.Date(), nullable=False),
    sa.Column('cleared_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('minutes_played', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('tackles_won', sa.Integer(), nullable=False),
    sa.Column('passes_completed', sa.Integer(), nullable=False),
    sa.Column('passes_attempted', sa.Integer(), nullable=False),
    sa.Column('match_rating', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['player_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'player_id', name='_player_match_uc')
    )
    op.create_table('scouting_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('scout_id', sa.Integer(), nullable=True),
    sa.Column('potential_rating', sa.String(length=10), nullable=False),
    sa.Column('tactical_awareness', sa.Text(), nullable=True),
    sa.Column('physical_assessment', sa.Text(), nullable=True),
    sa.Column('conclusion', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scout_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trial_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trial_session_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('performance_rating', sa.Integer(), nullable=True),
    sa.Column('scout_feedback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trial_session_id'], ['trial_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trial_attendance')
    op.drop_table('scouting_reports')
    op.drop_table('match_stats')
    op.drop_table('injury_logs')
    with op.batch_alter_table('player_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_profiles_primary_position'))
        batch_op.drop_index(batch_op.f('ix_player_profiles_last_name'))

    op.drop_table('player_profiles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('trial_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trial_sessions_session_date'))

    op.drop_table('trial_sessions')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_match_date'))

    op.drop_table('matches')
    # ### end Alembic commands ###
